sveltejs/cli

- .github/workflows/release.yml
This reverts commit 53bca8aac758b439e1ccc31a86f9bda771060378.
> Revert "chore: remove provenance (#110)"

- packages/adders/lucia/index.ts
> Update `lucia` url

- .changeset/five-rocks-yell.md
- packages/cli/commands/create.ts
> fix: quotes in `cd` output if necessary

- .changeset/nervous-pianos-sit.md
- packages/create/shared/+demo+checkjs/svelte.config.js
- packages/create/shared/+demo+typescript/svelte.config.js
- packages/create/shared/+typescript/svelte.config.js
- packages/create/templates/demo/src/app.d.ts
- packages/create/templates/demo/svelte.config.js
- packages/create/templates/library/src/app.d.ts
- packages/create/templates/minimal/src/app.d.ts
https://svelte.dev/docs/kit/integrations
```diff
- https://svelte.dev/docs/kit/integrations#preprocessors
+ https://svelte.dev/docs/kit/integrations
```
https://svelte.dev/docs/kit/types#app.d.ts
```diff
- https://svelte.dev/docs/kit/types#app
+ https://svelte.dev/docs/kit/types#app.d.ts
```
> chore: update documentation url hash

- .changeset/twenty-bees-mate.md
- packages/cli/commands/create.ts
> fix: adjust package manager `run` step in `create`

- .github/workflows/release.yml
I'm not sure this is everything we need to do, but it's at least part of it
> chore: set UPDATE_TEMPLATE_SSH_KEY

- .changeset/real-bobcats-act.md
- .changeset/yellow-sheep-guess.md
- .changeset/young-mice-battle.md
- packages/cli/CHANGELOG.md
- packages/cli/package.json
> Revert "Version Packages"

- .changeset/wicked-pots-exist.md
- packages/adders/lucia/index.ts
Fixes #261 by replacing base64 with base32
> Fix: Use base32 for IDs

- .github/workflows/docs-preview-create-request.yml
- documentation/docs/10-introduction/10-overview.md
This is supposed to trigger a preview deployment whenever there's a PR that updates the docs. Only way to test it is to merge it and make a PR with an innocuous change
> add workflow

- documentation/docs/10-introduction/10-overview.md
hopefully the final test, an end-to-end run that will create a preview deployment that shows up in this PR, with a branch that gets deleted once the PR is merged
> remove comment

- .changeset/late-bobcats-promise.md
- packages/addons/tailwindcss/index.ts
> chore: remove `aspect-ratio` plugin

- .changeset/modern-rules-watch.md
- packages/create/templates/demo/package.json
- packages/create/templates/demo/package.template.json
- packages/create/templates/library/package.template.json
- packages/create/templates/minimal/package.template.json
> feat: update templates to `vite@6`

- .changeset/popular-seas-argue.md
- package.json
- packages/addons/sveltekit-adapter/index.ts
> fix: allow selecting adapter auto

- .changeset/mean-turkeys-sit.md
- packages/addons/common.ts
> fix: use 'prettier' instead of ['flat/prettier']

- .changeset/flat-weeks-film.md
- packages/addons/prettier/index.ts
> fix: add bun lockfiles to `.prettierignore`

- .changeset/eighty-tools-own.md
- packages/create/templates/demo/package.json
- packages/create/templates/demo/package.template.json
- packages/create/templates/demo/src/routes/sverdle/+page.svelte
> chore: use writable derived in sverdle `demo` project

- .changeset/hip-brooms-yawn.md
- packages/addons/sveltekit-adapter/index.ts
> feat: remove `adapter-cloudflare-workers` and upgrade other adapters

- .changeset/happy-moles-glow.md
- community-addon-template/tests/setup/suite.ts
- documentation/docs/20-commands/10-sv-create.md
- documentation/docs/20-commands/20-sv-add.md
- packages/addons/_tests/_setup/suite.ts
- packages/cli/commands/add/index.ts
- packages/cli/commands/create.ts
- packages/cli/lib/testing.ts
- packages/cli/utils/package-manager.ts
> feat: adds `--install <package-manager>` flag to `create` and `add`

- .changeset/yummy-things-learn.md
- packages/create/templates/demo/package.template.json
- packages/create/templates/library/package.template.json
- packages/create/templates/minimal/package.template.json
PR for https://github.com/sveltejs/cli/pull/522#issuecomment-2800227299
https://github.com/advisories/GHSA-356w-63v5-8wf4
> security: upgrade vite to avoid CVE-2025-32395

- .changeset/clear-laws-dress.md
- packages/addons/drizzle/index.ts
Issue: https://github.com/sveltejs/cli/issues/570
> fix: removed unused import in `drizzle` schema to fix lint

- .changeset/social-areas-tell.md
- packages/addons/prettier/index.ts
Following https://github.com/sveltejs/cli/pull/618
> fix: update `static/` to `/static/` in `.prettierignore`

- .changeset/tangy-friends-camp.md
- packages/addons/tailwindcss/index.ts
> fix: tailwindcss & prettier conf

- .changeset/lazy-carrots-float.md
- packages/create/shared/+library/README.md
Closes #654 
This was missed while merging #396
> fix(create): update library docs to reflect proper `pack` command

- .changeset/tangy-deer-fetch.md
the changelog in https://github.com/sveltejs/cli/pull/657 looks off, this should improve it.
> fix changesets

- .changeset/hungry-waves-like.md
- packages/addons/eslint/index.ts
> fix(eslint): add `@types/node` in devDependencies
