sveltejs/cli

.changeset/stale-rockets-raise.md
packages/adders/drizzle/index.ts
packages/adders/lucia/index.ts
packages/cli/commands/add/index.ts
packages/cli/commands/add/workspace.ts
packages/cli/commands/create.ts
packages/cli/common.ts

closes #151
unifies the `packageManager` field such that the value that's passed to adders (for uses such as in `nextSteps`) is the same as the chosen PM from the user prompt

fix: consistent package manager detection

---

.changeset/small-bags-pull.md
packages/cli/commands/add/index.ts

related conversation
https://discord.com/channels/457912077277855764/1298479734606528628

Clarify CLI instructions

---

.changeset/silver-geese-punch.md
packages/adders/tailwindcss/index.ts
packages/cli/commands/add/index.ts

closes #220
This is a good instance where having [`runsAfter`](https://github.com/sveltejs/cli/pull/86) would've been useful. While `tailwindcss` doesn't require `prettier` to function, ensuring that it's executed _after_ `prettier` would've guaranteed that the `prettier-plugin-tailwindcss` is installed when they've both been selected
rather than bringing `runsAfter` back, I've tweaked the sorting order so that 2 adders that don't have `dependsOn` specified stay in place, which is just a temp fix
Re: Duplicate `@import` statements - this was another case where `"` vs `'` made a difference

fix: `tailwindcss` import insertions and execution order

---

.changeset/real-bobcats-act.md
packages/create/shared/README.md

The default `README.md` still has references to the older `create-svelte` package, whereas all code blocks got updated with `sv` CLI.

fix: update `README.md` generated by `sv create`

---

.changeset/yellow-sheep-guess.md
packages/cli/commands/add/index.ts
packages/cli/common.ts

fix: properly log error when dependency install fails

---

.changeset/sixty-sloths-kneel.md
packages/cli/commands/add/index.ts
packages/cli/common.ts

reverts #228
yarn and bun are now throwing errors because of this change. going to release as a hotfix for now.

fix: revert #228

---

.github/workflows/release.yml
packages/cli/package.json
packages/create/scripts/update-template-repo.sh

closes #243 
- Removed the `postpublish` script and moved the updater to its own workflow step
- Added a check to only commit new files when the working tree is dirty
- Template repo's commit message now references the `sv` version

chore: fix template repo updater

---

.github/workflows/sync-request.yml

This adds a workflow that _in theory_ will dispatch a sync request to the `sveltejs/svelte.dev` repo that, on merges to `main`, will create or update a PR like this one: https://github.com/sveltejs/svelte.dev/pull/729
The only way I can really test this is by merging this and pushing an innocuous docs change, so that's what I'll do

add sync request workflow

---

.changeset/nice-lemons-attend.md
packages/adders/lucia/index.ts

- Adds `setSessionTokenCookie()` and `deleteSessionTokenCookie()` (closes #122)
- Fixes sessions to be consistent with lucia-auth.com. This isn't a security issue, but the hashing part wasn't implement properly which negated the benefits it provided.
- Update `generateUserId()` to be consistent with `generateSessionToken()` and easier to deal with.
- Removed return types to be consistent with the rest of the codebase.
I haven't added change sets yet and I'm not sure how to test the adder.

fix: update lucia adder

---

.github/workflows/docs-preview-delete-request.yml

this will in theory delete preview branches on svelte.dev once PRs are closed/merged

add workflow for deleting branches

---

.github/workflows/docs-preview-create-request.yml
.github/workflows/docs-preview-delete-request.yml
documentation/docs/10-introduction/10-overview.md

This allows preview deployments to be created for PRs from external contributors

chore: use pull_request_target instead of pull_request event in workflows

---

.changeset/small-queens-press.md
packages/cli/commands/create.ts

closes #286
It's safe to assume that an add-on's preconditions will always be met as we only provide the add-ons that are valid for the current environment

fix: disable preconditions during `create`

---

.changeset/sharp-rocks-scream.md
packages/create/index.ts
packages/create/shared/+none/jsconfig.json

feat: add `jsconfig.json` to the 'no type checking' template

---

.changeset/fluffy-readers-attend.md
packages/clack-prompts/index.ts
packages/cli/utils/package-manager.ts

If the process for installing deps exits unexpectedly, the package manager's output is kept on screen. If it's successful, the output cleared.
demo:

feat: display package manager output during dependency installs

---

.changeset/modern-emus-wait.md
packages/clack-prompts/index.ts

Fixes a small bug where the output would grow larger than the current window's height, leaving undesirable text behind.

fix: limit dependency install's output window size

---

.changeset/eighty-bikes-yawn.md
packages/addons/eslint/index.ts

removed `@types/eslint` package from eslint addon as it is not required anymore
ref https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70735

chore: remove @types/eslint package from eslint addon

---

package.json
packages/core/package.json
pnpm-lock.yaml
rollup.config.js

Problem with package mentioned above first detect in #314. Based on the findings this issue was created: https://github.com/unplugin/unplugin-isolated-decl/issues/34
The generated code now looks fine, but intellisense and `tsc` are still not happy.
The problem assumably arises because the file extensions are now stripped, see [`unplugin-isolated-decl@0.8.1`](https://github.com/unplugin/unplugin-isolated-decl/releases/tag/v0.8.1). Everything seems to be working in the example project provided in the issue mentioned above, but not here.
Let's in example take a look at `packages\core\dist\index.d.ts` (after running `pnpm build` from the root):
```js
export { defineAddon, defineAddonOptions } from './addon/config';
// ...
export * as utils from './utils';
export type * from …
```

chore: update `unplugin-isolated-decl`

---

.changeset/six-moose-admire.md
packages/migrate/migrations/svelte-5/index.js

The new documentation site is now live ✨

chore: replace svelte-5-preview link

---

README.md
packages/cli/README.md
packages/migrate/README.md

I didn't know `sv create` had such comprehensive documentation.
Adding the package documentation link in the README will help.

docs: add cli documentation link

---

documentation/docs/20-commands/40-sv-migrate.md

closes https://github.com/sveltejs/cli/issues/283

docs: fix broken link

---

.changeset/silver-bees-pump.md
packages/addons/paraglide/index.ts

Closes #308 
Only works in combination with #335

fix: add paraglide output directory to `.gitignore`

---

.changeset/healthy-boxes-laugh.md
packages/addons/paraglide/index.ts

The paraglide demo contains sample code for a language switcher with typing in JSDoc.
Currently the typing is not working, as it is missing curly brackets.

Paraglide: Fix typing for newLanguage in demo code

---

.changeset/honest-bugs-brush.md
packages/create/templates/demo/package.template.json
packages/create/templates/minimal/package.template.json

feat: set app templates to `private` by default

---

.changeset/tender-donkeys-attack.md
documentation/docs/20-commands/40-sv-migrate.md
packages/migrate/README.md

Closes #348
Additionally re-orders the migrations inside the `packages/migrate/README.md` to the same order as displayed on the website, which seem way more logical.

docs: add `self-closing-tags` migration

---

.changeset/giant-peaches-run.md
documentation/docs/20-commands/20-sv-add.md
packages/addons/_config/official.ts
packages/addons/_tests/storybook/test.ts
packages/addons/_tests/sveltekit-adapter/test.ts
packages/addons/sveltekit-adapter/index.ts
packages/cli/commands/add/index.ts

closes #248
`sveltekit-adapter` installs and replaces existing SvelteKit adapters.
usage:
```shell
sv add --sveltekit-adapter <node|static|vercel|cloudflare-pages|cloudflare-workers|netlify>

feat: adds `sveltekit-adapter` add-on

---

.changeset/chatty-queens-judge.md
packages/cli/commands/create.ts

fix(create): Resolve package manager commands correctly in next steps

---

package.json
pnpm-lock.yaml

This removes the heavy `glob` library as a dependency from `@rollup/plugin-commonjs`, so that it's only pulled in via `sucrase` now.

chore: upgrade @rollup/plugin-commonjs to v28

---

.changeset/shy-pandas-learn.md
rollup.config.js

Detected by @benmccann in https://github.com/sveltejs/cli/pull/371
There is no sense to generate the sourcemaps in CI and publish them. Locally, this seems to save about 65 % of our bundle size.

fix: don't generate sourcemaps in CI

---

.changeset/lemon-cycles-mix.md
packages/addons/eslint/index.ts

Fixes #374
I used version `@eslint/js@^9.17.0` since that's what's installed on our pnpm lockfile for this project, but maybe we can require lower?

fix: add missing eslint import in generated package.json

---

documentation/docs/20-commands/40-sv-migrate.md

should be `$app/stores` not `$app/store`

fix typo with `"$app/stores"`

---

.changeset/sixty-shrimps-mate.md
packages/addons/paraglide/index.ts
packages/core/tests/js/common/jsdoc-comment/input.ts
packages/core/tests/js/common/jsdoc-comment/output.ts
packages/create/templates/demo/src/routes/Header.svelte

Companion for https://github.com/sveltejs/cli/pull/354 and https://github.com/sveltejs/kit/pull/13140 respectively
* uses `$app/state` in the paraglide addon
* uses `$app/state` in the `demo` template

feat: migrate to `$app/state`

---

.changeset/strange-ducks-melt.md
packages/migrate/migrations/svelte-5/index.js

This adds two new prompts to the Svelte migration:
- custom folder prompt (from multiselect); if selected you can specify what folders exactly to migrate. closes #390
- adds a way to skip migrating your components if you want to do it incrementally but still benefit from having your package.json and entry points migrated automatically

feat: allow sub path migration or none at all

---

.changeset/pretty-balloons-leave.md
packages/create/templates/library/package.template.json

The `prepack` lifecycle script runs before the [`npm pack`](https://docs.npmjs.com/cli/v10/using-npm/scripts#npm-pack) and `npm publish` commands.
By utilizing this:
1. the `prepublishOnly` lifecycle script can be removed, which contained an `npm` command.[^1]
2. it works with `npm pack`.
> [!NOTE]  
> The `publint@0.3` CLI does run the `pack` command, but it does not run the lifecycle scripts.
>
> So `&& publint` should be included at the end of the `prepack` script.
>
> This is correctly implemented from [`publint@0.3.2`](https://github.com/publint/publint/releases/tag/publint%400.3.2), thus the SemVer is updated to `^0.3.2`.
>
> - https://github.com/publint/publint/issues/129#issuecomment-2589151355
[^1]: I hope they are changed to [`node --run`](https://nodejs.org/api/cli.html#--run) …

chore: utilize prepack lifecycle script

---

.changeset/twelve-pets-film.md
packages/addons/tailwindcss/index.ts

Tailwind CSS plugins should be installed as `devDependencies` alongside `tailwindcss`.
```shell
npm install -D @tailwindcss/forms
```
https://github.com/tailwindlabs/tailwindcss-forms#installation

fix: tailwind plugins as dev dependencies

---

.changeset/friendly-lemons-shop.md
.changeset/late-rules-yell.md
.changeset/pretty-balloons-leave.md
.changeset/tiny-colts-trade.md
.changeset/twelve-pets-film.md
packages/cli/CHANGELOG.md
packages/cli/package.json

Revert "Version Packages"

---

.changeset/gold-cougars-report.md
packages/addons/vitest-addon/index.ts
packages/create/templates/demo/package.json
packages/create/templates/demo/package.template.json
packages/create/templates/library/package.template.json
packages/create/templates/minimal/package.template.json

`vitest@3` has been released. `vite@6` can be used.
- [`vitest@3.0.0`]: Support Vite 6
[`vitest@3.0.0`]: https://github.com/vitest-dev/vitest/releases/tag/v3.0.0
Previous attempts:
- https://github.com/sveltejs/cli/pull/340
- https://github.com/sveltejs/cli/pull/353 (reverts above PR)
Additional changes:
- Vitest add-on has been update to `^3.0.0`.
```
┌  Welcome to the Svelte CLI! (v0.6.13)
│
◇  Where would you like your project to be created?
│  ./
│
◇  Which template would you like?
│  SvelteKit minimal
│
◇  Add type checking with Typescript?
│  Yes, using Typescript syntax
│
◆  Project created
│
◇  What would you like to add to your project? (use arrow keys / space bar)
│  vitest
```
```shell
pnpm add @sveltejs/vite-plugin-svelte@latest vite@latest vitest@latest
pnpm test # works
pnpm …
```

chore: update vite and related packages

---

.changeset/proud-apples-watch.md
packages/cli/commands/check.ts
packages/cli/commands/migrate.ts
packages/cli/utils/common.ts

fix: forward exit code of external package commands

---

.changeset/angry-dingos-run.md
packages/create/templates/demo/package.template.json
packages/create/templates/library/package.template.json
packages/create/templates/minimal/package.template.json

closes https://github.com/sveltejs/cli/issues/388
see also https://github.com/sveltejs/kit/pull/13304
~~I went with `preprepare` as I believe it runs on solely on local installs (not installs from registry. though perhaps installs using git). Had previously been thinking about `prepare`, but that also runs on publish and we don't need to do it then~~
~~marked as draft as this currently only works on npm: https://github.com/pnpm/pnpm/issues/8987~~

chore: add prepare script to run `svelte-kit sync`

---

.changeset/three-humans-pay.md
packages/create/templates/demo/src/routes/sverdle/+page.svelte

This PR modifies the create-svelte default template to ensure `keydown` events while playing Sverdle correctly avoid making a request to the server if client-side JS is available. Apparently, the synthetic mouse event needs to bubble to trigger the `onclick` handler. If not, it triggers the `formaction` on the button instead.

fix: avoid server round trips when playing Sverdle with a keyboard

---

documentation/docs/20-commands/30-sv-check.md

Link to ticket: **No linked ticket**
Changed `argoument` to `argument`
Read `documentation/docs/20-commands/30-sv-check.md`
Spelling is correct
n/a
n/a

corrected spelling of 'argument'

---

.changeset/empty-geese-draw.md
.github/workflows/ci.yml
packages/addons/_tests/tailwindcss/test.ts
packages/addons/tailwindcss/index.ts

feat: add `tailwindcss` 4.0

---

.changeset/pretty-panthers-call.md
packages/addons/lucia/index.ts

fix: generate correct table defintion for `turso` in `lucia` demo

---

.changeset/config.json

fix: changsets ignores unpublished packages

---

.changeset/nine-phones-shout.md
packages/cli/utils/package-manager.ts

Relates https://github.com/sveltejs/cli/pull/432
Relates https://github.com/sveltejs/cli/pull/424
Relates https://github.com/sveltejs/cli/pull/388
I fixed the tests in my last commit in the other PR, but broke it for newly create projects. Here is the fix

fix: `onlyBuiltDependencies` not added on new projects

---

.changeset/happy-news-drive.md
packages/addons/_tests/sveltekit-adapter/test.ts
packages/addons/sveltekit-adapter/index.ts

Fixes https://github.com/sveltejs/cli/issues/430

Remove comment about adapter-auto once a specific sveltekit adapter is chosen

---

.changeset/nervous-apples-attack.md
packages/addons/drizzle/index.ts
packages/addons/eslint/index.ts
packages/addons/vitest-addon/index.ts

Created a PR similar to https://github.com/sveltejs/cli/pull/357
Only reviewed applied major dependency bumps:
- [`drizzle-orm@0.39`](https://github.com/drizzle-team/drizzle-orm/releases/tag/0.39.0)
- [`drizzle-orm@0.40`](https://github.com/drizzle-team/drizzle-orm/releases/tag/0.40.0)
- [`globals@16`](https://github.com/sindresorhus/globals/releases/tag/v16.0.0)
- [`jsdom@26`](https://github.com/jsdom/jsdom/releases/tag/26.0.0)

chore: update addon dependencies

---

.changeset/hungry-beds-speak.md
packages/addons/drizzle/index.ts

Closes #377 
Linked issue was suggesting only adding text for neon databases. After a second thought the current steps are not precise and may lead to unexpected results in most (non docker) cases.

fix: make `drizzle` next steps more precise

---

.changeset/two-crabs-bow.md
packages/addons/_tests/tailwindcss/test.ts
packages/addons/tailwindcss/index.ts

fix: re-add `tailwindcss` plugins

---

.changeset/lazy-boxes-compete.md
packages/addons/eslint/index.ts

Fixes the version added for `eslint-plugin-svelte`. It seems like a bad merge added duplicates.
Closes #457

fix: use `eslint-plugin-svelte` v3

---

.changeset/ninety-islands-cross.md
packages/addons/tailwindcss/index.ts

Fixes a bug where tailwind plugins wouldn't be added on subsequent `sv add tailwindcss` runs.

fix: allow `tailwindcss` plugins to be added after initial execution

---

.changeset/selfish-houses-retire.md
packages/create/templates/demo/src/routes/sverdle/+page.svelte

In this case, specifying a key doesn’t make much practical difference, but I added it because having ESLint errors right after creating the project looks bad.

chore: add keys to `{#each}` blocks

---

.changeset/tricky-icons-allow.md
packages/cli/lib/install.ts

fix: addons executed in the wrong order in certain circumstances

---

.changeset/swift-poets-wonder.md
packages/addons/drizzle/index.ts

closes #452 
This PR basically changes `src\lib\server\db\index.ts` from 
```js
export const db = drizzle(client);
```
to 
```js
export const db = drizzle(client, {
schema
});
```
For both mysql based  options (mysql2 and planetscale) another property [`mode`](https://orm.drizzle.team/docs/rqb#modes) is added to the config object. 
I' was unable to test the planetscale implementation though, as their pricing is off the charts.  We should consider dropping it in the future.

fix: pass `schema` to `drizzle` client for better type generation

---

community-addon-template/README.md
documentation/docs/10-introduction/20-faq.md
packages/cli/commands/add/fetch-packages.ts

'npm' should never be capitalized; the same goes for pnpm. (I also moved Yarn to the bottom of the list, reflecting its priority)

docs: lowercase npm and pnpm

---

.changeset/stupid-geckos-deliver.md
.gitignore
packages/create/shared/+library/README.md

closes https://github.com/sveltejs/cli/issues/498

chore: replace `create-svelte` in library template readme

---

.changeset/strange-islands-float.md
packages/migrate/migrations/svelte-5/index.js

Fixes #485 
This is the simplest approach I could think of--I know it can get a little hairy with all the versions of Svelte and SvelteKit out there. Still, I believe most of the logic is already in place with the CLI to make sure the user has the right versioning heading into the migration.
This only runs the app-state migration script if the user has SvelteKit. It doesn't really log anything or add any error handling--I'll leave those up to you if desired.
Also, I know you guys have a contributing guide on the docket, but I was wondering how exactly you test this CLI on your own projects. I ask because I ended up using `npm link` which is pretty standard, but I had to edit [these lines of code](https://github.com/sveltejs/cli/blob/d1f4432c0e31677ae754d50394547eeff820ddfe/packages/cli/com …

feat: added `app-state` migration into `svelte-5` migration

---

.changeset/rich-zebras-hunt.md
packages/addons/eslint/index.ts

close: https://github.com/sveltejs/cli/issues/481

chore: disable `no-undef` ESLint rule in TypeScript project

---

.changeset/tall-moons-marry.md
packages/cli/utils/package-manager.ts

Closes #502 
`p.select(` was actually throwing, which caused the formatting relevant source code to be skipped.
@hyunbinseo Could you please check if this works for you? `pkg-pr-new` url will be posted in a second.

fix: package manager detection in non interactive environments

---

.changeset/pretty-emus-breathe.md
packages/addons/prettier/index.ts

If the project already has a `.prettierrc` which is YAML, we will currently throw an uncaught exception trying to parse it as JSON.
This change means we will skip such files and only try to mutate JSON configs.

fix(prettier): skip non-JSON prettierrc config

---

.changeset/twelve-lizards-warn.md
packages/addons/eslint/index.ts

chore: do not add redundant `ignores` property to `eslint` config

---

.changeset/poor-ducks-own.md
packages/addons/drizzle/index.ts

Changed `await mysql.createConnection()` to `mysql.createPool()`
--
When using `mysql.createConnection()`, the connection will end up getting closed if it's not used for longer than [wait_timeout](https://dev.mysql.com/doc/refman/8.4/en/server-system-variables.html#sysvar_wait_timeout). Error message from mysql2 after a period of inactivity can be seen below:
```
Error: Can't add new command when connection is in closed state
```
Since drizzle doesn't handle any of the connection, you would need to juggle the database client and drizzle around before querying to make sure the connection to the database wasn't closed.
I haven't experienced this with postgres.js, as it's seemingly using [pools by default](https://github.com/porsager/postgres?tab=readme-ov-file#the-connection-pool).
If not …

fix: mysql2 closed state (drizzle addon)

---

.changeset/late-rockets-argue.md
packages/create/templates/demo/package.template.json
packages/create/templates/library/package.template.json
packages/create/templates/minimal/package.template.json

Despite https://github.com/sveltejs/cli/pull/520, an outdated `adapter-auto` is added:
```json
{
"devDependencies": {
"@sveltejs/adapter-auto": "^4.0.0",
```
```
┌  Welcome to the Svelte CLI! (v0.8.1)
│
◇  Which template would you like?
│  SvelteKit minimal
│
◇  Add type checking with TypeScript?
│  Yes, using TypeScript syntax
│
◆  Project created
│
◇  What would you like to add to your project? (use arrow keys / space bar)
│  none
```
Probably because the adapter is not installed as an add-on?

chore: use the latest adapter-auto

---

.changeset/honest-eels-fly.md
packages/addons/sveltekit-adapter/index.ts

The Cloudflare adapter is no longer Cloudflare Pages-specific. It currently supports Cloudflare Workers Static Assets too
https://svelte.dev/docs/kit/adapter-cloudflare

fix: rename cloudflare-pages to cloudflare

---

.changeset/odd-bikes-like.md
packages/addons/common.ts
packages/addons/drizzle/index.ts
packages/addons/storybook/index.ts

closes #509
This is an alternative to #536 and #539 where `@types/node` is added to `devDependencies` by the `drizzle` and `storybook` add-ons. 
The version of `@types/node` is derived from the version of node from the current running process. Since `@types/node` only publishes types for `lts` versions of node, we'll need to install the nearest `lts` version for `current` releases. To do this, we'll just decrement the major number by one (and chop off the minor and patch numbers) to target the previous `lts` release version (note that we can detect whether a release is `lts` or `current` based on the if the major is an even or odd number, respectively)
For example: if the installed node version is `22.14.0` (`lts`), then `^22` will be added to the `package.json`. If the node version is …

fix: add `@types/node` to `drizzle` and `storybook` add-ons

---

packages/addons/_tests/drizzle/test.ts
packages/addons/drizzle/index.ts
packages/core/tests/js/common/expression-from-string/output.ts
packages/core/tests/js/common/expression-from-string/run.ts
packages/core/tests/js/index.ts
packages/core/tooling/js/common.ts

A bit of the code here was unused. See https://github.com/sveltejs/cli/pull/555
~~I haven't gotten a chance to test this yet, but thought I'd share my progress before I have to run for the day. Manuel thought that we might need to tweak `expressionFromString` to delete the `Literal.raw property` so that it can pick the proper quote type. I've not checked that yet and assume we'll need to update it~~

chore: leverage expressionFromString more in drizzle adder

---

CONTRIBUTING.md

docs: contributing.md

---

.changeset/loose-colts-sin.md
packages/addons/storybook/index.ts
packages/cli/lib/install.ts
packages/core/addon/config.ts

Supersedes #547 
Closes #550 
As described in the issue, we now have an add-on that needs to run after some other add-ons. This feature was previously removed as part of #86 since it was not used anymore.
In contrary to the original implementation in #86, if an add-on calls `dependsOn`, `runsAfter` is also called in order to only have one property based on which the ordering of the add-ons should occur.

feat: expose `runsAfter` to add-ons

---

.changeset/clever-chicken-compete.md
packages/addons/lucia/index.ts

closes: #493 
Updated to use pattern similar to login utilities. This pattern matches the SvelteKit docs and allows people to see it in use straight away when adding the lucia addon.

fix: lucia require user redirect moved to auth guard function

---

.changeset/dull-pens-wash.md
packages/addons/common.ts

fix: account for Node `current` releases with even majors when resolving `@types/node` version

---

.changeset/new-bats-dress.md
packages/addons/drizzle/index.ts
packages/cli/commands/add/index.ts

closes #573
since we iterate and execute all of the `setup` functions from every add-on (mainly to determine which add-ons to show in the add-on selection prompt, relative to the current environment), drizzle wasn't playing nice in non-sveltekit projects due to a non-null assertion (oops!).

fix: add `kit` check in `drizzle` add-on

---

.changeset/cuddly-rings-travel.md
packages/addons/vitest-addon/index.ts

closes #579 
alternative to #580 
As discussed in #580 this is a regression in `vitest`, so let's pin it for now: https://github.com/vitest-dev/vitest/issues/8120

fix(vitest): `mount(...)` not available

---

.changeset/social-paws-wash.md
packages/addons/vitest-addon/index.ts

see https://github.com/sveltejs/cli/pull/584 and https://github.com/vitest-dev/vitest/issues/8120

fix(vitest): unpin to ^3.2.3 after it fixed a regression

---

.changeset/evil-comics-cover.md
packages/addons/_tests/vitest/test.ts
packages/addons/tailwindcss/index.ts
packages/addons/vitest-addon/index.ts
packages/cli/commands/add/index.ts
packages/core/addon/options.ts
packages/core/tests/js/object/create-from-primitives/output.ts
packages/core/tests/js/object/create-from-primitives/run.ts
packages/core/tooling/js/object.ts

Supports `vitest` browser mode. Makes the setup more flexible by asking the user to add component / unit testing.
Adds a new `object.createFromPrimitives` to core that should help us find the right balance for https://github.com/sveltejs/cli/issues/557. We should all `object.create` calls in the future and try to use this wherever possible.
todo:

feat(vitest): vitest browser mode

---

.changeset/silent-timers-carry.md
packages/addons/drizzle/index.ts
packages/addons/lucia/index.ts
packages/addons/package.json
pnpm-lock.yaml

Set up a project earlier and it output:
> Run **deno run db:push** to update your database schema
...which is wrong for deno.
`package-manager-detector` seems to be used in other spots for this, so I added it here as well.
Tried to find all places using `run`, but only found it in `lucia` & `drizzle`.
---
Regarding changesets, I found this statement in `CONTRIBUTING.md` a bit confusing:
> Only publish a change set if it is in 'sv' or 'svelte-migrate' as all other packages are bundled.
The changes are in `addons` but it _affects_ `sv`...

fix: resolve to `task` instead of `run` in addon instructions for `deno`

---

packages/cli/lib/index.ts

We do have `create` that works flawlessly. But we do have `installAddon` that is unusable at this point in time, since it requires addons, that you can not export from anywhere. 
Since all of this is an undocumented api, im not too concerned.

chore: make `installAddon()` work

---

.changeset/brown-peas-shop.md
documentation/docs/30-add-ons/60-devtools-json.md
packages/addons/devtools-json/index.ts
packages/cli/commands/add/index.ts
packages/cli/commands/create.ts
packages/cli/lib/install.ts
packages/core/addon/config.ts

- you won't get that error log anymore, but will get the message in https://github.com/sveltejs/kit/pull/13905

docs: improvements to the `devtools-json` docs

---

eslint.config.js
packages/core/tsconfig.json

This PR intends to remove the eslint errors that show up in the IDE about certain .ts files not being included by the tsconfig.json . An example of this is `packages/core/tests/utils.ts`.
More about project service replacing the project setting: https://typescript-eslint.io/packages/parser/#projectservice

chore: use project service for typescript-eslint to auto-detect tsconfig.json

---

.github/workflows/ci.yml

The vast majority of our flakiness when we run tests in CI is due to some weird storybook cli error related to fetching (_i think_). 
This PR serves as a quick test to see if we can at least alleviate some of the flakiness by prefetching the CLI before we run our test suite so it's stored in pnpm's cache.
edit:
This seems to work. Rerunning the tests in CI has yielded no errors and is 10/11 on successful runs (one of the runs failed because of a vitest `onTaskUpdate` error with mdsvex, so it's unrelated).

chore: prefetch storybook cli during CI tests

---

.changeset/blue-islands-eat.md
packages/cli/commands/add/index.ts
packages/cli/commands/create.ts

feat: combine next steps prompt for `create`

---

.changeset/dull-items-sort.md
.github/workflows/ci.yml
packages/addons/storybook/index.ts

According to Jeppe this is the correct way to do it. As of now, `storybook init` is just calling `create-storybook` according to him.

chore: use `create-storybook` instead of `storybook init`

---

CONTRIBUTING.md
documentation/docs/10-introduction/10-overview.md
documentation/docs/20-commands/10-sv-create.md
documentation/docs/20-commands/20-sv-add.md
documentation/docs/20-commands/30-sv-check.md
documentation/docs/20-commands/40-sv-migrate.md
documentation/docs/30-add-ons/03-devtools-json.md
documentation/docs/30-add-ons/05-drizzle.md
documentation/docs/30-add-ons/10-eslint.md
documentation/docs/30-add-ons/15-lucia.md
documentation/docs/30-add-ons/20-mdsvex.md
documentation/docs/30-add-ons/25-paraglide.md
documentation/docs/30-add-ons/30-playwright.md
documentation/docs/30-add-ons/35-prettier.md
documentation/docs/30-add-ons/40-storybook.md
documentation/docs/30-add-ons/45-sveltekit-adapter.md
documentation/docs/30-add-ons/50-tailwind.md
documentation/docs/30-add-ons/55-vitest.md
packages/cli/README.md
packages/create/package.json
packages/create/scripts/update-template-repo.sh
packages/create/shared/+library/README.md
packages/create/shared/README.md
packages/migrate/README.md

Every time that I have read the default readme I did not like the fact that generic shell commands were labeled as bash and I have changed it. After the third time I have decided to fix it upstream.
Also there are some minor improvements that are bash-related.
Everything is explained in the commit messages.

Improve (ba)sh usage, mainly in docs

---

.github/workflows/ci.yml
packages/addons/_tests/storybook/test.ts

Relates https://github.com/sveltejs/cli/pull/622
Relates https://github.com/sveltejs/svelte-ecosystem-ci/pull/32
In direct comparison to #622 this has the disadvantage, that this also run's locally. We could check via the `CI` env variable, but I don't think that would help to reproduce pipeline failures locally.  On the other hand, this is an improvement in comparison to #622 because it allows our tests to be run everywhere, without requiring explicit setup. This is in example the case in `svelte-ecosystem-ci` (https://github.com/sveltejs/svelte-ecosystem-ci/pull/32)
If this works the way I think it should (I will check in the pipeline), I would personally consider this as a slight improvement.

chore: improved storybook prefetching

---

.changeset/hot-roses-call.md
packages/create/shared/+typescript/tsconfig.json

Accompanying https://github.com/sveltejs/kit/pull/14026
This PR changes the comment in the create template's tsconfig.json file to prefer the kit config setting for extending the tsconfig file instead of overriding the includes and excludes settings.
Open to a better explanation/wording of why the setting should be used.

chore(create): recommend the `kit.typescript.config` setting instead of copying from the generated config

---

packages/addons/_tests/drizzle/test.ts

If the `drizzle` test is aborted using `ctrl+c`, we'll want to cleanup any remaining running containers.

chore(drizzle): cleanup docker containers when the process is aborted

---

.changeset/sour-wings-taste.md
packages/addons/devtools-json/index.ts
packages/addons/paraglide/index.ts
packages/addons/tailwindcss/index.ts
packages/addons/vitest-addon/index.ts
packages/cli/commands/add/utils.ts
packages/cli/commands/add/workspace.ts
packages/core/addon/workspace.ts

Typescript project doesn't mean `ts` files

---

.changeset/major-moles-cut.md
packages/cli/commands/migrate.ts

Closes #675 
This has been an oversight in one of the last pull requests for the migrate package

fix(migrate): `npx sv migrate` fails to run

---

.changeset/fancy-cars-stand.md
packages/addons/drizzle/index.ts
packages/addons/lucia/index.ts
packages/addons/paraglide/index.ts

chore: change dependencies to devDependencies in addons

---

.changeset/light-taxis-share.md
packages/cli/commands/add/index.ts

fix(add): allow passing add-on as argument that dependsOn another

---

.changeset/empty-toys-admire.md
packages/addons/eslint/index.ts

fix(eslint): update eslint to `^9.22.0` and use `defineConfig`

---

.changeset/eager-schools-allow.md
packages/addons/_tests/vitest/test.ts
packages/addons/vitest-addon/index.ts
packages/core/tests/js/imports/find-import/output.ts
packages/core/tests/js/imports/find-import/run.ts
packages/core/tests/js/imports/remove-import/input.ts
packages/core/tests/js/imports/remove-import/output.ts
packages/core/tests/js/imports/remove-import/run.ts
packages/core/tests/js/vite/with-alias/input.ts
packages/core/tests/js/vite/with-alias/output.ts
packages/core/tests/js/vite/with-alias/run.ts
packages/core/tests/js/vite/without-defineConfig/output.ts
packages/core/tooling/js/exports.ts
packages/core/tooling/js/imports.ts
packages/core/tooling/js/vite.ts

fix(vitest): now import `defineConfig` from `vitest/config`

---

.changeset/solid-singers-help.md
packages/create/playground.ts
packages/create/test/playground.ts

--from-playground will create projects with experimental.async

---

packages/create/scripts/update-template-repo-contents.js
packages/create/scripts/update-template-repo.sh

Looking at https://github.com/sveltejs/cli/actions/runs/18222249563/job/51884670580 there is an issue with the new build. (it's internal thing)
I addapted the script. Should work now.
But looking https://github.com/sveltejs/kit-template-default last deployed was `0.8.21` ! _(the one after is `0.9`)_ Maybe an issue with the `bot` permissions?

fix push to `kit-template-default`
